version: '2.1'

services:
  py:
    build: .
    volumes:
    - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
    - http.host=0.0.0.0
    # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
